### PR TITLE
Fix(users-roles): dont remove last admin

### LINKED ISSUE #454: Security Flaw: Ability to delete the last Admin role/user
The system currently allows a user to delete the "Admin" role or the last remaining Admin user, which can lead to a complete lockout from administrative functions.

Steps to Reproduce:
    Log in as an Admin.
    Create a new "Cashier" role and create a new user with that role.
    Delete the Admin role (while still logged in).
    The system logs the user out.

    Attempting to log back in as Admin fails (PIN not recognized), and the Cashier account lacks sufficient permissions to restore the Admin role.

Expected Behavior:
The system should prevent the deletion of the "Admin" role if it is the only administrative role available. Similarly, it should not allow the deletion of the last Admin user to prevent permanent lockouts.

### PR DESCRIPTION
**Pull request by Vidarte-Alberto**
This pull request improves error handling and user feedback for role and user management in the Store admin UI. It introduces more specific toasts for conflict cases (such as attempting to delete the last admin), refactors HTTP error handling logic for clarity and consistency, and expands test coverage for these scenarios. Additionally, it updates and clarifies several English locale strings.

**Error Handling and User Feedback Improvements:**

* Added specific toast notifications for conflict errors (HTTP 409), such as when trying to delete the last admin user or role, in both the roles and users management UIs. Toasts now display more informative messages and use appropriate colors for warnings and errors. [[1]](diffhunk://#diff-88441c6f84992611b0af673cafa9cb42f516f4fb7fbd4bc76d362b2c15f372f1R102-R108) [[2]](diffhunk://#diff-88441c6f84992611b0af673cafa9cb42f516f4fb7fbd4bc76d362b2c15f372f1L114-R126) [[3]](diffhunk://#diff-4e3a42a445269b62d464f33656c0894065e8165e5c2a7a843699fd7d6e27f33fR9-R47) [[4]](diffhunk://#diff-4e3a42a445269b62d464f33656c0894065e8165e5c2a7a843699fd7d6e27f33fL33-R112) [[5]](diffhunk://#diff-4e3a42a445269b62d464f33656c0894065e8165e5c2a7a843699fd7d6e27f33fR126-R142) [[6]](diffhunk://#diff-4e3a42a445269b62d464f33656c0894065e8165e5c2a7a843699fd7d6e27f33fR152-R168)
* Refactored HTTP error handling in `useRoles.jsx` and `useUsers.jsx` by introducing helper functions to standardize error creation and response checking, making the code more robust and easier to maintain. [[1]](diffhunk://#diff-1f1f164a389e719289f843ebef96977a148746f799370c56903edc05224143a0R8-R19) [[2]](diffhunk://#diff-1f1f164a389e719289f843ebef96977a148746f799370c56903edc05224143a0R51) [[3]](diffhunk://#diff-1f1f164a389e719289f843ebef96977a148746f799370c56903edc05224143a0R87) [[4]](diffhunk://#diff-1f1f164a389e719289f843ebef96977a148746f799370c56903edc05224143a0L104-R119) [[5]](diffhunk://#diff-4e3a42a445269b62d464f33656c0894065e8165e5c2a7a843699fd7d6e27f33fR9-R47)

**Testing Enhancements:**

* Added and updated tests to verify that conflict errors (such as deleting the last admin) are properly thrown and that the correct toast is shown to the user. [[1]](diffhunk://#diff-121f38e74f2b82719573b8bbc45f76919f10299546fd20e89e3b107da0b275d5R157-R176) [[2]](diffhunk://#diff-f87ba63dd32f176109d9b0b5c1cc6152b6e28e40ea6e893252ab31f3960c886dR3) [[3]](diffhunk://#diff-f87ba63dd32f176109d9b0b5c1cc6152b6e28e40ea6e893252ab31f3960c886dR15-R22) [[4]](diffhunk://#diff-f87ba63dd32f176109d9b0b5c1cc6152b6e28e40ea6e893252ab31f3960c886dR194-R214)

**Localization Updates:**

* Expanded and clarified English locale strings for toasts, roles, and wallet-related UI, including new messages for last admin conflict scenarios and improved formatting for readability. [[1]](diffhunk://#diff-cd6cabb661b4c8b90544c74da065b262bdcc623769c53a5f7b5997be352ee0b9R82-R83) [[2]](diffhunk://#diff-cd6cabb661b4c8b90544c74da065b262bdcc623769c53a5f7b5997be352ee0b9R97-R108) [[3]](diffhunk://#diff-cd6cabb661b4c8b90544c74da065b262bdcc623769c53a5f7b5997be352ee0b9L103-R118) [[4]](diffhunk://#diff-cd6cabb661b4c8b90544c74da065b262bdcc623769c53a5f7b5997be352ee0b9L16-R32) [[5]](diffhunk://#diff-cd6cabb661b4c8b90544c74da065b262bdcc623769c53a5f7b5997be352ee0b9L143-R159) [[6]](diffhunk://#diff-cd6cabb661b4c8b90544c74da065b262bdcc623769c53a5f7b5997be352ee0b9L757-R780) [[7]](diffhunk://#diff-cd6cabb661b4c8b90544c74da065b262bdcc623769c53a5f7b5997be352ee0b9L777-R797) [[8]](diffhunk://#diff-cd6cabb661b4c8b90544c74da065b262bdcc623769c53a5f7b5997be352ee0b9L970-R996) [[9]](diffhunk://#diff-cd6cabb661b4c8b90544c74da065b262bdcc623769c53a5f7b5997be352ee0b9L984-R1014)

### CODE REVIEW

File: client/src/components/pages/Store/locales/en.js [hunk 1]
```diff
@@ -13,18 +13,23 @@ const storeEn = {
...
+    receiveAmountDescription:
+      "Enter <b>5000</b> as the amount. This covers the fee to open your Lightning channel.",
     receiveDescTitle: "Step 2: Description",
-    receiveDescDescription: "Type <b>open channel</b> as the description to identify this payment.",
+    receiveDescDescription:
+      "Type <b>open channel</b> as the description to identify this payment.",
     receiveButtonTitle: "Step 3: Create & Scan",
-    receiveButtonDescription: "Click <b>Create Lightning Invoice</b>, then scan the QR code that appears with your Lightning wallet to open the channel.",
+    receiveButtonDescription:
+      "Click <b>Create Lightning Invoice</b>, then scan the QR code that appears with your Lightning wallet to open the channel.",
```
Comment (Sharmaz) [inline client/src/components/pages/Store/locales/en.js]: Fix or disable your formatter, this changes has nothing to do with your tasks

**Review by Sharmaz — CHANGES_REQUESTED** [review]
Fix or disable your formatter. Revert those changes

**Review by Sharmaz — APPROVED** [review]
LGTM!!

**Review by ca-ruz — APPROVED** [review]
LGTM!
